### PR TITLE
Adding codelist definitions and changelog

### PR DESCRIPTION
**Pull request by timgdavies**
Adding codelist definitions and change log

### CODE REVIEW

**Comment by jpmckinney** [comment]
Just need to add a newline at end of bidStatus.csv (I can make the error message clearer) and decide whether 'Required by' makes sense to include (see https://github.com/open-contracting/ocds-extensions/issues/55)

**Comment by jpmckinney** [comment]
These tests can be run locally same as test_json.py, just replace `test_json` with `test_csv`.

**Comment by timgdavies** [comment]
Thanks @jpmckinney - Edits made and pulled a copy of maintenance scripts to run them locally in future. 

If you are happy with these changes - please do merge.

**Comment by jpmckinney** [comment]
If happy with wording change in https://github.com/open-contracting/ocds-extensions/issues/24#issuecomment-361291067 I can add that commit then merge.

**Comment by timgdavies** [comment]
@jpmckinney Yes please - use these wordings and merge.

**Pull request merged**
