### PR TITLE
Add URL of issue repository to README.md

### PR DESCRIPTION
**Pull request by edugomez**

### CODE REVIEW

**Comment by jpmckinney** [comment]
See (outdated?) comment in https://github.com/open-contracting/standard-development-handbook/pull/48 about the text. Also, I have the means to add this to all the readmes and create pull requests programmatically, in case you're doing it manually.

**Comment by jpmckinney** [comment]
PR descriptions for these PRs should also link to https://github.com/open-contracting/standard-development-handbook/issues/23 (can also be done programmatically).

**Comment by edugomez** [comment]
> I have the means to add this to all the readmes and create pull requests programmatically, in case you're doing it manually.

Great, please do so, I'm closing this PR.

**Comment by jpmckinney** [comment]
Done, see https://github.com/open-contracting/standard-development-handbook/issues/23

**Pull request closed without merging**
